<script src="<?php echo asset('public/js/jquery-1.10.2.min.js'); ?>"></script>
<script src="<?php echo asset('public/js/jquery-1.8.3.js'); ?>"></script>
<script src="<?php echo asset('public/js/jquery-migrate-1.2.1.min.js '); ?>"></script>
<script src="<?php echo asset('public/js/jquery-ui.js '); ?>"></script><!--loading bootstrap js-->
<script src="<?php echo asset('public/vendors/bootstrap/js/bootstrap.min.js '); ?>"></script>
<script src="<?php echo asset('public/vendors/bootstrap-hover-dropdown/bootstrap-hover-dropdown.js '); ?>"></script>
<script src="<?php echo asset('public/vendors/metisMenu/jquery.metisMenu.js '); ?>"></script>
<script src="<?php echo asset('public/vendors/jquery-cookie/jquery.cookie.js '); ?>"></script>
<script src="<?php echo asset('public/vendors/iCheck/custom.min.js '); ?>"></script>
<script src="<?php echo asset('public/js/jquery.menu.js '); ?>"></script>
<script src="<?php echo asset('public/vendors/moment/moment.js '); ?>"></script>
<script src="<?php echo asset('public/vendors/slimScroll/jquery.slimscroll.js'); ?>"></script>
<script src="<?php echo asset('public/vendors/iCheck/icheck.min.js'); ?>"></script>
<script src="<?php echo asset('public/vendors/iCheck/custom.min.js'); ?>"></script>
<script src="<?php echo asset('public/vendors/bootstrap-datepicker/js/bootstrap-datepicker.js '); ?>"></script>
<script src="<?php echo asset('public/vendors/bootstrap-daterangepicker/daterangepicker.js '); ?>"></script><!--CORE JAVASCRIPT-->
<script src="<?php echo asset('public/js/main.js '); ?>"></script><!--LOADING SCRIPTS FOR PAGE-->
<script src="<?php echo asset('public/vendors/jquery-validate/jquery.validate.min.js'); ?>"></script>
<script src="<?php echo asset('public/js/form-validation.js'); ?>"></script>
<script src="<?php echo asset('public/js/functions.js'); ?>"></script>